# Generated by Django 5.0.6 on 2026-06-29 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RescueZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la zona')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitud')),
                ('state_ve', models.CharField(db_index=True, max_length=100, verbose_name='Estado venezolano')),
                ('risk_type', models.CharField(choices=[('collapse', 'Derrumbe'), ('landslide', 'Deslizamiento'), ('flood', 'Inundación'), ('fire', 'Incendio'), ('other', 'Otro')], db_index=True, max_length=20, verbose_name='Tipo de riesgo')),
                ('technical_needs', models.JSONField(default=list, help_text='Lista de equipamiento/personal técnico requerido. Ej: ["Retroexcavadora", "Apuntaladores"]', verbose_name='Necesidades técnicas')),
                ('missing_supplies', models.JSONField(default=list, help_text='Suministros de emergencia requeridos en la zona.', verbose_name='Suministros faltantes')),
                ('volunteers_needed', models.IntegerField(default=0, verbose_name='Voluntarios requeridos')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('attended', 'Atendida'), ('closed', 'Cerrada')], db_index=True, default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Zona de Rescate',
                'verbose_name_plural': 'Zonas de Rescate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, help_text='Descripción de habilidades o disponibilidad del voluntario.', verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
            ],
            options={
                'verbose_name': 'Solicitud de Voluntario',
                'verbose_name_plural': 'Solicitudes de Voluntarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
