# Generated by Django 5.0.6 on 2026-06-29 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rescue_zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuezone',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_rescue_zones', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por'),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Voluntario'),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_requests', to='rescue_zones.rescuezone', verbose_name='Zona de rescate'),
        ),
        migrations.AddIndex(
            model_name='rescuezone',
            index=models.Index(fields=['status'], name='rescue_zone_status_d63257_idx'),
        ),
        migrations.AddIndex(
            model_name='rescuezone',
            index=models.Index(fields=['risk_type'], name='rescue_zone_risk_ty_6f615a_idx'),
        ),
        migrations.AddIndex(
            model_name='rescuezone',
            index=models.Index(fields=['state_ve'], name='rescue_zone_state_v_032cde_idx'),
        ),
        migrations.AddIndex(
            model_name='rescuezone',
            index=models.Index(fields=['-created_at'], name='rescue_zone_created_1bf9c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerrequest',
            unique_together={('zone', 'volunteer')},
        ),
    ]
