# Generated by Django 5.0.6 on 2026-06-29 23:56

import apps.missing_people.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200, verbose_name='Nombre completo')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('cedula', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Cédula')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.missing_people.models.missing_person_photo_path, verbose_name='Foto')),
                ('last_known_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitud última ubicación')),
                ('last_known_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitud última ubicación')),
                ('last_known_location_description', models.TextField(verbose_name='Descripción de última ubicación conocida')),
                ('state_ve', models.CharField(db_index=True, max_length=100, verbose_name='Estado venezolano')),
                ('status', models.CharField(choices=[('missing', 'Desaparecido'), ('found', 'Localizado'), ('deceased', 'Fallecido')], db_index=True, default='missing', max_length=20, verbose_name='Estado')),
                ('reporter_phone', models.CharField(max_length=20, verbose_name='Teléfono del reportante')),
                ('located_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de localización')),
                ('found_condition', models.CharField(blank=True, choices=[('safe', 'Ileso'), ('injured', 'Herido'), ('deceased', 'Fallecido'), ('unknown', 'Desconocido')], max_length=20, null=True, verbose_name='Condición al encontrar')),
                ('found_location_type', models.CharField(blank=True, choices=[('hospital', 'Hospital'), ('shelter', 'Refugio'), ('risk_zone', 'Zona de Riesgo'), ('home', 'Domicilio'), ('other', 'Otro')], max_length=20, null=True, verbose_name='Tipo de lugar donde fue encontrado')),
                ('found_location_description', models.TextField(blank=True, null=True, verbose_name='Descripción del lugar donde fue encontrado')),
                ('locator_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del localizador')),
                ('duplicate_hash', models.CharField(db_index=True, help_text='SHA256 hash de nombre normalizado + edad para detección de duplicados.', max_length=64, verbose_name='Hash de duplicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Persona Desaparecida',
                'verbose_name_plural': 'Personas Desaparecidas',
                'ordering': ['-created_at'],
            },
        ),
    ]
