# Generated by Django 5.0.6 on 2026-06-29 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missing_people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='located_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='located_persons', to=settings.AUTH_USER_MODEL, verbose_name='Localizado por'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_missing', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['status'], name='missing_peo_status_cbca6b_idx'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['state_ve'], name='missing_peo_state_v_b60ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['duplicate_hash'], name='missing_peo_duplica_00c8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['-created_at'], name='missing_peo_created_995b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['cedula'], name='missing_peo_cedula_5790f3_idx'),
        ),
    ]
