# Generated by Django 5.0.6 on 2026-06-29 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Correo electrónico único del usuario.', max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula', models.CharField(blank=True, help_text='Formato: V-12345678 o E-12345678', max_length=15, null=True, unique=True, verbose_name='Cédula')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('CITIZEN', 'Ciudadano')], db_index=True, default='CITIZEN', max_length=20, verbose_name='Rol')),
                ('is_verified_health_worker', models.BooleanField(default=False, verbose_name='Trabajador de salud verificado')),
                ('is_verified_shelter_manager', models.BooleanField(default=False, verbose_name='Administrador de refugios verificado')),
                ('is_verified_org_donor', models.BooleanField(default=False, verbose_name='Organización donante verificada')),
                ('auth_provider', models.CharField(choices=[('google', 'Google'), ('manual', 'Manual')], default='manual', max_length=20, verbose_name='Proveedor de autenticación')),
                ('google_id', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Google ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['role'], name='users_user_role_36d76d_idx'), models.Index(fields=['cedula'], name='users_user_cedula_a06c0e_idx'), models.Index(fields=['google_id'], name='users_user_google__98b509_idx')],
            },
        ),
    ]
