# Generated by Django 5.0.6 on 2026-06-30 20:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trigram_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_requested', models.CharField(choices=[('health_worker', 'Trabajador de Salud'), ('shelter_manager', 'Gestor de Refugio'), ('org_donor', 'Organización Donante')], max_length=50, verbose_name='Rol Solicitado')),
                ('document', models.ImageField(upload_to='verifications/', verbose_name='Documento de Identidad/Credencial')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del Administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Verificación',
                'verbose_name_plural': 'Solicitudes de Verificación',
                'ordering': ['-created_at'],
            },
        ),
    ]
