# Generated by Django 5.0.6 on 2026-07-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_web_collaborator',
            field=models.BooleanField(default=False, verbose_name='Colaborador Web Verificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified_health_worker',
            field=models.BooleanField(default=False, verbose_name='Trabajador de Salud Verificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified_org_donor',
            field=models.BooleanField(default=False, verbose_name='Organización / Donante Verificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified_shelter_manager',
            field=models.BooleanField(default=False, verbose_name='Gestor de Refugio Verificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMIN', 'Administrador'), ('CITIZEN', 'Ciudadano')], db_index=True, default='CITIZEN', max_length=20, verbose_name='Rol'),
        ),
    ]
