# Generated by Django 5.0.6 on 2026-06-29 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Refugio')),
                ('type', models.CharField(choices=[('hotel', 'Hotel / Hospedaje'), ('camp', 'Campamento Temporal'), ('open_area', 'Zona Abierta / Polideportivo'), ('community_center', 'Centro Comunitario'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de Refugio')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitud')),
                ('address', models.TextField(verbose_name='Dirección Detallada')),
                ('state_ve', models.CharField(max_length=100, verbose_name='Estado')),
                ('status', models.CharField(choices=[('open', 'Abierto (Con Cupos)'), ('full', 'Lleno (Capacidad Máxima)'), ('closed', 'Cerrado / No Operativo')], default='open', max_length=20, verbose_name='Estado del Refugio')),
                ('current_capacity', models.IntegerField(default=0, verbose_name='Capacidad Actual')),
                ('max_capacity', models.IntegerField(default=0, verbose_name='Capacidad Máxima')),
                ('missing_supplies', models.JSONField(blank=True, default=list, verbose_name='Insumos Críticos Faltantes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Refugio',
                'verbose_name_plural': 'Refugios',
                'ordering': ['-updated_at'],
            },
        ),
    ]
