# Generated by Django 5.0.6 on 2026-06-29 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeismicEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Identificador único del evento en la fuente de datos.', max_length=100, unique=True, verbose_name='ID del evento externo')),
                ('magnitude', models.DecimalField(decimal_places=1, help_text='Magnitud en la escala local o momento.', max_digits=4, verbose_name='Magnitud')),
                ('depth_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Profundidad (km)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitud')),
                ('epicenter_name', models.TextField(help_text='Descripción textual de la ubicación del epicentro.', verbose_name='Nombre del epicentro')),
                ('magnitude_type', models.CharField(default='ML', help_text='ML=Local, Mw=Momento, Mb=ondas de cuerpo, etc.', max_length=10, verbose_name='Tipo de magnitud')),
                ('source', models.CharField(choices=[('USGS', 'USGS'), ('TERRAQUAKE', 'TerraQuake'), ('MANUAL', 'Manual')], db_index=True, default='USGS', max_length=50, verbose_name='Fuente de datos')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='URL del evento en la fuente')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Fecha y hora del evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado en sistema')),
            ],
            options={
                'verbose_name': 'Evento Sísmico',
                'verbose_name_plural': 'Eventos Sísmicos',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['-occurred_at'], name='seismology__occurre_bcbe77_idx'), models.Index(fields=['magnitude'], name='seismology__magnitu_2fb34d_idx'), models.Index(fields=['source'], name='seismology__source_73a150_idx'), models.Index(fields=['latitude', 'longitude'], name='seismology__latitud_4531c2_idx')],
            },
        ),
    ]
