# Generated by Django 5.0.6 on 2026-06-29 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Comercial o Razón Social')),
                ('type', models.CharField(choices=[('company', 'Empresa / Comercio'), ('brand', 'Marca'), ('donor', 'Donador Particular'), ('individual', 'Persona Natural / Voluntario Técnico')], default='company', max_length=20, verbose_name='Tipo de Colaborador')),
                ('description', models.TextField(verbose_name='Descripción de la Ayuda u Ofrecimiento')),
                ('contact_info', models.JSONField(default=dict, verbose_name='Información de Contacto')),
                ('services_offered', models.JSONField(blank=True, default=list, verbose_name='Servicios o Insumos Ofrecidos')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='allies_logos/', verbose_name='Logo o Imagen de Referencia')),
                ('active_from', models.DateTimeField(auto_now_add=True, verbose_name='Activo Desde')),
                ('active_until', models.DateTimeField(blank=True, null=True, verbose_name='Activo Hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo Actualmente?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Aliado',
                'verbose_name_plural': 'Perfiles de Aliados',
                'ordering': ['-created_at'],
            },
        ),
    ]
