# Generated by Django 5.0.6 on 2026-07-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Módulo')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='Slug (identificador)')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Módulo del Sistema',
                'verbose_name_plural': 'Módulos del Sistema',
                'ordering': ['name'],
            },
        ),
    ]
