# Generated by Django 5.0.6 on 2026-06-29 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Recurso')),
                ('url', models.URLField(max_length=500, verbose_name='Enlace / URL')),
                ('social_network', models.CharField(blank=True, max_length=100, null=True, verbose_name='Red Social o Usuario (ej. @resilienciave)')),
                ('description', models.CharField(max_length=140, verbose_name='Descripción Corta (máx 140 caracteres)')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='crisis_screenshots/', verbose_name='Captura de Pantalla / Imagen de Referencia')),
                ('category', models.CharField(choices=[('app', 'Aplicación Móvil / PWA'), ('website', 'Sitio Web de Ayuda'), ('social', 'Red Social / Canal de Difusión'), ('ngo', 'Organización No Gubernamental (ONG)'), ('other', 'Otro Recurso')], default='website', max_length=20, verbose_name='Categoría')),
                ('is_approved', models.BooleanField(default=False, verbose_name='¿Está Aprobado por Moderación?')),
                ('moderation_flags', models.JSONField(blank=True, default=list, verbose_name='Banderas de Moderación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recurso de Crisis',
                'verbose_name_plural': 'Recursos de Crisis',
                'ordering': ['-created_at'],
            },
        ),
    ]
