# Generated by Django 5.0.6 on 2026-06-29 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Centro')),
                ('type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clínica'), ('medical_post', 'Puesto de Atención Médica')], default='hospital', max_length=20, verbose_name='Tipo de Centro')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitud')),
                ('address', models.TextField(verbose_name='Dirección Detallada')),
                ('state_ve', models.CharField(max_length=100, verbose_name='Estado')),
                ('status', models.CharField(choices=[('operational', 'Operativo (Con Capacidad)'), ('critical', 'Crítico (Insumos/Personal Limitados)'), ('closed', 'Fuera de Servicio / Colapsado')], default='operational', max_length=20, verbose_name='Estado de Operatividad')),
                ('is_attending', models.BooleanField(default=True, verbose_name='¿Está Atendiendo Emergencias?')),
                ('missing_supplies', models.JSONField(blank=True, default=list, verbose_name='Insumos Críticos Faltantes')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Teléfono de Contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centro de Salud',
                'verbose_name_plural': 'Centros de Salud',
                'ordering': ['-updated_at'],
            },
        ),
    ]
